# Generated by Django 5.0.1 on 2024-02-20 04:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0025_admin_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='address',
            field=models.CharField(default='address', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='admin',
            name='age',
            field=models.IntegerField(default=20, null=True),
        ),
        migrations.AlterField(
            model_name='admin',
            name='city',
            field=models.CharField(default='city', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='admin',
            name='country',
            field=models.CharField(default='country', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='admin',
            name='dob',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='admin',
            name='image',
            field=models.ImageField(default='hospital.png', upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='lastname',
            field=models.CharField(default='lastname', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='admin',
            name='postalcode',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='lastname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
