# Generated by Django 5.0.1 on 2024-04-21 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0030_appointment_hospital_alter_appointment_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.CharField(choices=[('abc', 'abc'), ('mno', 'mno')], default='address', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='village',
            field=models.CharField(choices=[('abc', 'abc'), ('mno', 'mno')], max_length=50),
        ),
    ]
